server:
  port: 8080
  max-http-header-size: 16KB

jwt:
  access-expiration: 15m
  refresh-expiration: 7d
  key-alias: jwt-key
  keystore-password: ${JWT_KEYSTORE_PASSWORD}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  service-sid: ${TWILIO_SERVICE_SID} # For Verify API
  from-number: +1234567890 # Fallback number
  rate-limit:
    max-attempts: 5
    window-duration: 10m

gcp:
  storage:
    project-id: your-project-id
    bucket-name: user-avatars
    credentials-location: classpath:gcp-credentials.json

logging:
  level:
    root: INFO
    org.springframework: WARN
    reactor.netty: DEBUG

graalvm:
  native:
    memory:
      max-heap: 1G
      stack-size: 1M

netty:
  leak-detection: DISABLED
  max-order: 3
  thread:
    boss: 2
    worker: 8

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://pgbouncer:6432/usersdb?prepareThreshold=0
    username: ${DB_USER}
    password: ${DB_PASS}
    pool:
      max-size: 500
      initial-size: 50
      max-idle-time: 30m

  liquibase:
    change-log: classpath:/db/changelog/master.xml
    enabled: true

  pgbouncer:
    pool-mode: transaction
    default-pool-size: 200
    reserve-pool-size: 50

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 512
        max-idle: 256
        min-idle: 64
        max-wait: 10s

  mail:
    host: ${SMTP_HOST:smtp.example.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:user}
    password: ${SMTP_PASSWORD:pass}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
